### ISSUE TITLE
doesn't work with Vimeo embedded videos 

### ISSUE THREAD

**Issue by danpritts** [benedictchen/google-chrome-html5video-controls#7]
viewing videos on vimeo.com works

but when a site embeds a vimeo video, things aren't happy.  the controller shows up at first, but doesn't work.  after a while, it disappears.  Meanwhile, every click is interpreted by the vimeo player.

Here is an example:

https://www.kickstarter.com/projects/1598272670/chip-the-worlds-first-9-computer/description
(not the top video, which is flash - lower down, "pocket chip demonstration").  

thanks for this extension. it is awesome.

**Comment by benedictchen** [comment]
It was an annoying issue where Vimeo overlays an invisible div on top of everything and intercepts all clicks. It should be solved, please wait as the Chrome Dev store propagates the changes.
